name: Build on Ubuntu 22.04

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: "25 3 1 * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    timeout-minutes: 360

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build script
        run: |
          sh -ex ./build.sh

      - name: Upload to GitHub Releases
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: date +%Y%m%d
          prerelease: false
          title: "Latest Build"
          files: |
            ./serenity/Build/x86_64/grub_disk_image.tar.bz2
